USE x_marks_the_spot;

CREATE TABLE MILESTONES(
	MILESTONE_ID INT PRIMARY KEY NOT NULL UNIQUE,
	MILESTONE_NAME VARCHAR(255) NOT NULL,
	MILESTONE_ICON VARCHAR(255) NOT NULL,
    MILESTONE_POINTS INT NOT NULL
);

CREATE TABLE USERS(
	USER_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    FIRST_NAME VARCHAR(255),
	LAST_NAME VARCHAR(255),
	EMAIL VARCHAR(255) NOT NULL UNIQUE,
	USERNAME VARCHAR(255) NOT NULL UNIQUE,
	PASSWORD_HASH VARCHAR(255) NOT NULL,
    USER_POINTS INT DEFAULT 0,
    MILESTONE_REACHED INT DEFAULT 0,
	FOREIGN KEY (MILESTONE_REACHED) REFERENCES MILESTONES(MILESTONE_ID)
);

CREATE TABLE GAMEPLAYS(
	GAME_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT UNIQUE,
    GAME_DATE DATETIME NOT NULL,
    GAME_FINISHED TINYINT,
    USER_ID INT NOT NULL,
	GAME_TOPIC VARCHAR(255) NOT NULL,
    USER_SCORE INT NOT NULL,
	FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE QUESTIONS (
    QUESTION_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    QUESTION VARCHAR(255) NOT NULL,
    QUESTION_TYPE VARCHAR(50) NOT NULL,
    QUESTION_LEVEL INT NOT NULL,
    ANSWER VARCHAR(255)
);

CREATE TABLE COUNTRIES (
    COUNTRY_ID INT NULL AUTO_INCREMENT PRIMARY KEY,
    COUNTRY_NAME VARCHAR(100),
    FLAG VARCHAR(255),
    CONTINENT VARCHAR(50),
    CAPITAL VARCHAR(100),
	COUNTRY_LANGUAGE VARCHAR(100),
    CURRENCY VARCHAR(100),
    EQUATOR VARCHAR(100), -- North or South
    PRIME_MERIDIAN VARCHAR(100), -- East or West
    CLIMATE VARCHAR(255),
    CLOSEST_OCEAN VARCHAR(100)
);


