CREATE SCHEMA IF NOT EXISTS x_marks_the_spot;

USE x_marks_the_spot;

CREATE TABLE MILESTONES(
	MILESTONE_ID INT PRIMARY KEY NOT NULL UNIQUE,
	MILESTONE_NAME VARCHAR(255) NOT NULL,
	MILESTONE_ICON VARCHAR(255) NOT NULL,
    MILESTONE_POINTS INT NOT NULL
);

CREATE TABLE USERS(
	USER_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    FIRST_NAME VARCHAR(255),
	LAST_NAME VARCHAR(255),
	EMAIL VARCHAR(255) NOT NULL UNIQUE,
	USERNAME VARCHAR(255) NOT NULL UNIQUE,
	PASSWORD_HASH VARCHAR(255) NOT NULL,
    USER_POINTS INT,
    MILESTONE_REACHED INT DEFAULT 0,
	FOREIGN KEY (MILESTONE_REACHED) REFERENCES MILESTONES(MILESTONE_ID)

);

CREATE TABLE GAMEPLAYS(
	GAME_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT UNIQUE,
    GAME_DATE DATETIME NOT NULL,
    GAME_FINISHED TINYINT,
    USER_ID INT NOT NULL,
	GAME_TOPIC VARCHAR(255) NOT NULL,
    USER_SCORE INT NOT NULL,
	FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- Insert initial data for 0 milestones
INSERT INTO MILESTONES(MILESTONE_ID, MILESTONE_NAME, MILESTONE_ICON, MILESTONE_POINTS) VALUES
	(0, "Game Created", "N/A", 0);

-- Insert initial data for user table
INSERT INTO USERS(FIRST_NAME, LAST_NAME, EMAIL, USERNAME, PASSWORD_HASH, USER_POINTS, MILESTONE_REACHED) VALUES
	("Sarah", "Lee", "sarahlee@gmail.com", "sarah123", "password", 500, 0);
INSERT INTO USERS(FIRST_NAME, LAST_NAME, EMAIL, USERNAME, PASSWORD_HASH, USER_POINTS, MILESTONE_REACHED) VALUES
	("David", "Lu", "david@gmail.com", "david01", "password", 1000, 0);